### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/codelab-js-libraries-and-jquery-plugins#1]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](http://famous-fact.surge.sh/) and meets the following [project](http://lansingcodelab.com/lessons/js-libraries-and-jquery-plugins/1) criteria:
- [x] Use at least 1 jQuery plugin for visible effect (you can use one listed on the last page of the lesson, one recommended by a mentor, or one that you just find by Googling)
- [x] Use at least 1 non-jQuery JavaScript library for visible effect (you can use one listed on the last page of the lesson, one recommended by a mentor, or one that you just find by Googling)

**Comment by chrisvfritz** [comment]
I noticed you use the minified version of WOW, which is great! The `.min` before the `.js` means that this version of the library has had all the unnecessary comments and characters removed from it, so that it has a smaller file size for browsers to download. **Try to also find a minified version of FitText.**

I also noticed that some of the indentation in your file isn't quite right. It looks like the culprit is probably pasted in code that had tabs in it. Fortunately, there's a trusty [Atom plugin](https://atom.io/packages/tabs-to-spaces) that can **convert any accidentally inserted tabs to spaces** when you save a file. You can install plugins at the `Install` tab of the settings menu, which you can access with `Ctrl`-`,`. Don't forget to read the instructions for the plugin, so that you can configure it the way you want.

Otherwise, this is looking very good! I can't put my finger on why, but I'm very excited to get my hands on this product, assuming it will be tangible. :smiley:

**Comment by KatieMFritz** [comment]
@chrisvfritz  should be fixed now.

**Comment by KatieMFritz** [comment]
@chrisvfritz Also, I think your rewrite of the lesson is solid. Nice work.

**Comment by chrisvfritz** [comment]
:shipit: Looking much better! I notice [an extra space on this line still](https://github.com/KatieMFritz/codelab-js-libraries-and-jquery-plugins/blob/master/index.html#L32), but I'll let it slide. :smile_cat:
